#!/bin/sh
# Wrapper script around pandoc / markdown2pdf
# Provides templates to apply with pdf processing
# Copyright Claes Holmerson 2010, GPL licensed (see COPYING for details)
#Find this directory
# template_home=$(dirname $(readlink -f $0))
#template_home=$(cd `dirname $0`; pwd)
template_home=templates
paper=a4paper
hmargin=3cm
vmargin=3.5cm
fontsize=12pt
#fontsize=11pt
#fontsize=12pt
# PingFang SC
# mainfont="Adobe Fangsong Std"
# sansfont=Corbel
# monofont=Consolas
mainfont="Songti TC"
sansfont="WenQuanYi Zen Hei Sharp"
monofont="WenQuanYi Zen Hei Sharp"
language=english
#language=swedish
nohyphenation=false
columns=onecolumn
#columns=twocolumn
geometry=portrait
#geometry=landscape
alignment=flushleft
#alignment=flushright
#alignment=center
#-V CJKmainfont=SimSun

toc=3
pandoc --pdf-engine=xelatex --template=$template_home/default.latex \
-V language=$language \
-V paper=$paper -V hmargin=$hmargin -V vmargin=$vmargin \
-V mainfont="$mainfont" -V sansfont="$sansfont" -V monofont="$monofont" \
-V geometry=$geometry -V alignment=$alignment -V columns=$columns \
-V fontsize=$fontsize -V nohyphenation=$nohyphenation \
-V toc=$toc \
$@
